### ISSUE TITLE
TypeError: forward() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by chandagrover** [amitt1236/Deep_Cut#1]
Dear Author,

Thank You for making available github code for DeepCut for public use. 

Please help in resolving the below error. I am getting this error while I am running the example.ipynb

File ../..//gnn_pool.py:39, in GNNpool.forward(self, data, A)
     37 x, edge_index, edge_atrr = data.x, data.edge_index, data.edge_attr
     38 print("x.shape = ", x.shape,"edge_index.shape = ", edge_index.shape, "edge_atrr.shape = " , edge_atrr.shape)
---> 39 x = self.convs(x, edge_index, edge_atrr)  # applying con5v
     40 x = F.elu(x)
     42 # pass feats through mlp

File ../../Deep_Cut/env/lib/python3.8/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() takes 3 positional arguments but 4 were given

Thanks.

**Comment by amitt1236** [comment]
Hi, I think it's related to the torch geometric version. try: torch_geometric==2.0.4.
theres also an interactive collab notebook that is working, theres an icon in the ReadMe.

good luck, please update if this is the problem, so I could fix the requirement file.

Thanks.

**Comment by chandagrover** [comment]
Yes. It worked. Thank You.

**Comment by chandagrover** [comment]
Thank You. It worked.
